import "src/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Script from "next/script";

import { TRPCReactProvider } from "src/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        <Script id="theme-init" strategy="beforeInteractive">
          {`
            (() => {
              const storageKey = "open-skule-theme";
              const storedTheme = window.localStorage.getItem(storageKey);
              const systemTheme = window.matchMedia("(prefers-color-scheme: dark)").matches
                ? "dark"
                : "light";
              const theme = storedTheme ?? systemTheme;

              document.documentElement.classList.toggle("dark", theme === "dark");
            })();
          `}
        </Script>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
